name: boneca

services:
  # Production service
  boneca:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=Boneca
      - VERSION=0.1.0
      - API_PREFIX=/api/v1
    networks:
      - boneca-network
    profiles:
      - prod

  # Development service
  boneca-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["/app/src/scripts/entrypoint-dev.sh"]
    command: ["sleep", "infinity"]
    environment:
      - PROJECT_NAME=Boneca
      - VERSION=0.1.0
      - API_PREFIX=/api/v1
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    networks:
      - boneca-network
    profiles:
      - dev
    working_dir: /app

networks:
  boneca-network:
    name: boneca-network
